[build-system]
requires = [
    "setuptools>=63",
    "setuptools_scm[toml]>=7.0.5",
    "wheel",
]

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "post-tag"
local_scheme = "node-and-date"
write_to = "src/__version__.py"